In [33]:
import numpy as np
table = np.random.randint(0, high=2, size=(4,3))
print(table)

[[1 1 0]
 [0 1 1]
 [0 0 0]
 [1 1 0]]


# target: $\log{\frac{p_{i,j}}{p_{i} \times p_{j}}}$

### joint prob: $p_{i, j}$

In [34]:
p_table = table / table.sum()
print(p_table)

[[0.16666667 0.16666667 0.        ]
 [0.         0.16666667 0.16666667]
 [0.         0.         0.        ]
 [0.16666667 0.16666667 0.        ]]


### marginal prob: $p_{i}, p_{j}$

In [77]:
# marginal prob for each row
p_row = table.sum(axis=1)
p_col = table.sum(axis=0)

print(p_row)
print(p_col)

[3 3 3 3]
[4 4 4]


### $\dfrac{1}{p_{i} \times p_{j}}$

In [78]:
# inverse for product
p_row = np.diag(np.array([0 if elem== 0 else 1/elem for elem in p_row]))
p_col = np.diag(np.array([0 if elem== 0 else 1/elem for elem in p_col]))
print(p_row)
print(p_col)

[[0.33333333 0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.33333333 0.        ]
 [0.         0.         0.         0.33333333]]
[[0.25 0.   0.  ]
 [0.   0.25 0.  ]
 [0.   0.   0.25]]


# $\frac{p_{i,j}}{p_{i} \times p_{j}}$

In [81]:
PMI = p_row.dot(table).dot(p_col)
print(PMI)

[[0.08333333 0.08333333 0.08333333]
 [0.08333333 0.08333333 0.08333333]
 [0.08333333 0.08333333 0.08333333]
 [0.08333333 0.08333333 0.08333333]]


# why need diag?

In [62]:
table = np.array([[1,1,1],
                  [1,1,1],
                  [1,1,1],
                  [1,1,1]])
row_sum = table.sum(axis=1)
col_sum = table.sum(axis=0)
print(table)
print(row_sum)
print(col_sum)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[3 3 3 3]
[4 4 4]



### step1.
$\dfrac{\text{table}}{\text{row_sum}} = \text{np.dot(row_sum_reci, table)}$

In [69]:
row_sum_reci = np.diag(np.array([0 if elem == 0 else 1/elem for elem in row_sum]))
print(row_sum_reci)
print(np.dot(row_sum_reci, table))

[[0.33333333 0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.33333333 0.        ]
 [0.         0.         0.         0.33333333]]
[[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]]


### step2.
$\dfrac{\text{table}}{\text{col_sum}} = \text{np.dot(table, col_sum_reci)}$

In [70]:
col_sum_reci = np.diag(np.array([0 if elem == 0 else 1/elem for elem in col_sum]))
print(col_sum_reci)
print(np.dot(table, col_sum_reci))

[[0.25 0.   0.  ]
 [0.   0.25 0.  ]
 [0.   0.   0.25]]
[[0.25 0.25 0.25]
 [0.25 0.25 0.25]
 [0.25 0.25 0.25]
 [0.25 0.25 0.25]]


### step3. 
$\dfrac{\text{table}}{\text{row_sum x col_sum}} = \text{row_sum_reci.dot(table).dot(col_sum_reci)}$

In [73]:
row_sum_reci.dot(table).dot(col_sum_reci)

array([[0.08333333, 0.08333333, 0.08333333],
       [0.08333333, 0.08333333, 0.08333333],
       [0.08333333, 0.08333333, 0.08333333],
       [0.08333333, 0.08333333, 0.08333333]])